#version 460
layout(local_size_x = 1, local_size_y = 1) in;
layout(binding = 1, rgba8) uniform image2D inputImage;
layout(binding = 2, rgba8) uniform image2D outputImage;

void main()
{
    vec4 color = vec4(0.0);
    for(int dX = -1; dX <= 1; ++dX) {
        for(int dY = -1; dY <= 1; ++dY) {		
            color += imageLoad(inputImage, ivec2(gl_GlobalInvocationID.xy) + ivec2(dX, dY));
        }
    }
    imageStore(outputImage, ivec2(gl_GlobalInvocationID.xy), color / 9);
}
